from flask import Flask, jsonify
from flask_cors import CORS
from datetime import datetime

app = Flask(__name__)
CORS(app)

@app.route('/api/time')
def timenow():
    answer = {}
    now = datetime.now()
    answer['timestamp'] = datetime.timestamp(now)
    answer['abbreviated_weekday'] = now.strftime("%a")
    answer['weekday'] = now.strftime("%A")
    answer['weekday_number'] = now.strftime("%w")
    answer['decimal_day_of_month_zeropadded'] = now.strftime("%d")
    answer['decimal_day_of_month'] = now.strftime("%-d")
    answer['abbreviated_month'] = now.strftime("%b")
    answer['month'] = now.strftime("%B")
    answer['decimal_month_zeropadded'] = now.strftime("%m")
    answer['decimal_month'] = now.strftime("%-m")
    answer['decimal_year_wocentury_zeropadded'] = now.strftime("%y")
    answer['decimal_year_wocentury'] = now.strftime("%-y")
    answer['decimal_year'] = now.strftime("%Y")
    answer['decimal_hour_24_zeropadded'] = now.strftime("%H")
    answer['decimal_hour_24'] = now.strftime("%-H")
    answer['decimal_hour_12_zeropadded'] = now.strftime("%I")
    answer['decimal_hour_12'] = now.strftime("%-I")
    answer['locales_AMPM'] = now.strftime("%p")
    answer['decimal_minutes_zeropadded'] = now.strftime("%M")
    answer['decimal_minutes'] = now.strftime("%-M")
    answer['decimal_seconds_zeropadded'] = now.strftime("%S")
    answer['decimal_seconds'] = now.strftime("%-S")
    answer['decimal_microsecond_zeropadded'] = now.strftime("%f")
    answer['utc_offset'] = now.strftime("%z")
    answer['timezone'] = now.strftime("%Z")
    answer['decimal_dayofyear_zeropadded'] = now.strftime("%j")
    answer['decimal_dayofyear'] = now.strftime("%-j")
    answer['decimal_weeknumber_sunday'] = now.strftime("%U")
    answer['decimal_weeknumber_monday'] = now.strftime("%W")
    answer['locales_datetime'] = now.strftime("%c")
    answer['locales_date'] = now.strftime("%x")
    answer['locales_time'] = now.strftime("%X")
    return jsonify(answer)

@app.route('/api/time/<int:requestedtimestamp>')
def gettime(requestedtimestamp):
    answer = {}
    now = datetime.fromtimestamp(int(requestedtimestamp))
    answer['timestamp'] = datetime.timestamp(now)
    answer['abbreviated_weekday'] = now.strftime("%a")
    answer['weekday'] = now.strftime("%A")
    answer['weekday_number'] = now.strftime("%w")
    answer['decimal_day_of_month_zeropadded'] = now.strftime("%d")
    answer['decimal_day_of_month'] = now.strftime("%-d")
    answer['abbreviated_month'] = now.strftime("%b")
    answer['month'] = now.strftime("%B")
    answer['decimal_month_zeropadded'] = now.strftime("%m")
    answer['decimal_month'] = now.strftime("%-m")
    answer['decimal_year_wocentury_zeropadded'] = now.strftime("%y")
    answer['decimal_year_wocentury'] = now.strftime("%-y")
    answer['decimal_year'] = now.strftime("%Y")
    answer['decimal_hour_24_zeropadded'] = now.strftime("%H")
    answer['decimal_hour_24'] = now.strftime("%-H")
    answer['decimal_hour_12_zeropadded'] = now.strftime("%I")
    answer['decimal_hour_12'] = now.strftime("%-I")
    answer['locales_AMPM'] = now.strftime("%p")
    answer['decimal_minutes_zeropadded'] = now.strftime("%M")
    answer['decimal_minutes'] = now.strftime("%-M")
    answer['decimal_seconds_zeropadded'] = now.strftime("%S")
    answer['decimal_seconds'] = now.strftime("%-S")
    answer['decimal_microsecond_zeropadded'] = now.strftime("%f")
    answer['utc_offset'] = now.strftime("%z")
    answer['timezone'] = now.strftime("%Z")
    answer['decimal_dayofyear_zeropadded'] = now.strftime("%j")
    answer['decimal_dayofyear'] = now.strftime("%-j")
    answer['decimal_weeknumber_sunday'] = now.strftime("%U")
    answer['decimal_weeknumber_monday'] = now.strftime("%W")
    answer['locales_datetime'] = now.strftime("%c")
    answer['locales_date'] = now.strftime("%x")
    answer['locales_time'] = now.strftime("%X")
    return jsonify(answer)
    
